# 02 - Datenqualität und Duplikate prüfem
Der in Notebook 01 inventarisierte TLFS23-Datenbestand wird auf technische Lesbarkeit, Bildformat und identische Inhalte geprüft. Die Rohdaten werden dabei nicht verändert. Der vollständige Audit bildet die Grundlage für die spätere Datenbereinigung.

In [1]:
from pathlib import Path
import sys
import pandas as pd
from IPython.display import display

here = Path.cwd().resolve()
PROJECT_ROOT = next((p for p in (here, *here.parents)
                     if (p / "notebooks").is_dir() and (p / "data").is_dir()), None)
if PROJECT_ROOT is None:
    raise FileNotFoundError("Projektordner mit notebooks/ und data/ fehlt.")
if not (PROJECT_ROOT / "src/tlfs23/data.py").is_file():
    raise FileNotFoundError("Den Ordner src/tlfs23 aus dem Paket ins Projekt kopieren.")
sys.path.insert(0, str(PROJECT_ROOT / "src"))
from tlfs23 import data as d
from tlfs23.common import paths, read_csv, read_json, write_json

P = paths(PROJECT_ROOT)
print("Projekt:", PROJECT_ROOT)

inventory = d.inventory(PROJECT_ROOT)
print("Inventarisierte Bilder:", len(inventory))

Projekt: /Users/sharu/Documents/DBU/tamil-finger-sign-mlops
Inventarisierte Bilder: 255158

## 2. Bilder prüfen
Der vollständige Audit dekodiert alle inventarisierten Bilder. Bereits geprüfte, unveränderte Dateien können aus dem Audit-Cache wiederverwendet werden.

In [2]:
AUDIT_MODE = "full"
audit, summary = d.audit(PROJECT_ROOT, mode=AUDIT_MODE, per_class=5)
display(pd.DataFrame([{
    "Modus": summary["audit_mode"],
    "Gepruefte Dateien": summary["n_files_audited"],
    "Nicht lesbar": summary["n_unreadable_files"],
    "Exakte Duplikatgruppen": summary["n_exact_duplicate_groups"],
}]))

Bildpruefung: 500/255158 (500 aus Cache)
Bildpruefung: 1000/255158 (1000 aus Cache)
Bildpruefung: 1500/255158 (1500 aus Cache)
Bildpruefung: 2000/255158 (2000 aus Cache)
Bildpruefung: 2500/255158 (2500 aus Cache)
Bildpruefung: 3000/255158 (3000 aus Cache)
Bildpruefung: 3500/255158 (3500 aus Cache)
Bildpruefung: 4000/255158 (4000 aus Cache)
Bildpruefung: 4500/255158 (4500 aus Cache)
Bildpruefung: 5000/255158 (5000 aus Cache)
Bildpruefung: 5500/255158 (5500 aus Cache)
Bildpruefung: 6000/255158 (6000 aus Cache)
Bildpruefung: 6500/255158 (6500 aus Cache)
Bildpruefung: 7000/255158 (7000 aus Cache)
Bildpruefung: 7500/255158 (7500 aus Cache)
Bildpruefung: 8000/255158 (8000 aus Cache)
Bildpruefung: 8500/255158 (8500 aus Cache)
Bildpruefung: 9000/255158 (9000 aus Cache)
Bildpruefung: 9500/255158 (9500 aus Cache)
Bildpruefung: 10000/255158 (10000 aus Cache)
Bildpruefung: 10500/255158 (10500 aus Cache)
Bildpruefung: 11000/255158 (11000 aus Cache)
Bildpruefung: 11500/255158 (11500 aus Cache)
Bildpruefung: 12000/255158 (12000 aus Cache)
Bildpruefung: 12500/255158 (12500 aus Cache)
Bildpruefung: 13000/255158 (13000 aus Cache)
Bildpruefung: 13500/255158 (13500 aus Cache)
Bildpruefung: 14000/255158 (14000 aus Cache)
Bildpruefung: 14500/255158 (14500 aus Cache)
Bildpruefung: 15000/255158 (15000 aus Cache)
Bildpruefung: 15500/255158 (15500 aus Cache)
Bildpruefung: 16000/255158 (16000 aus Cache)
Bildpruefung: 16500/255158 (16500 aus Cache)
Bildpruefung: 17000/255158 (17000 aus Cache)
Bildpruefung: 17500/255158 (17500 aus Cache)
Bildpruefung: 18000/255158 (18000 aus Cache)
Bildpruefung: 18500/255158 (18500 aus Cache)
Bildpruefung: 19000/255158 (19000 aus Cache)
Bildpruefung: 19500/255158 (19500 aus Cache)
Bildpruefung: 20000/255158 (20000 aus Cache)
Bildpruefung: 20500/255158 (20500 aus Cache)
Bildpruefung: 21000/255158 (21000 aus Cache)
Bildpruefung: 21500/255158 (21500 aus Cache)
Bildpruefung: 22000/255158 (22000 aus Cache)
Bildpruefung: 22500/255158 (22500 aus Cache)
Bildpruefung: 23000/255158 (23000 aus Cache)
Bildpruefung: 23500/255158 (23500 aus Cache)
Bildpruefung: 24000/255158 (24000 aus Cache)
Bildpruefung: 24500/255158 (24500 aus Cache)
Bildpruefung: 25000/255158 (25000 aus Cache)
Bildpruefung: 25500/255158 (25500 aus Cache)
Bildpruefung: 26000/255158 (26000 aus Cache)
Bildpruefung: 26500/255158 (26500 aus Cache)
Bildpruefung: 27000/255158 (27000 aus Cache)
Bildpruefung: 27500/255158 (27500 aus Cache)
Bildpruefung: 28000/255158 (28000 aus Cache)
Bildpruefung: 28500/255158 (28500 aus Cache)
Bildpruefung: 29000/255158 (29000 aus Cache)
Bildpruefung: 29500/255158 (29500 aus Cache)
Bildpruefung: 30000/255158 (30000 aus Cache)
Bildpruefung: 30500/255158 (30500 aus Cache)
Bildpruefung: 31000/255158 (31000 aus Cache)
Bildpruefung: 31500/255158 (31500 aus Cache)
Bildpruefung: 32000/255158 (32000 aus Cache)
Bildpruefung: 32500/255158 (32500 aus Cache)
Bildpruefung: 33000/255158 (33000 aus Cache)
Bildpruefung: 33500/255158 (33500 aus Cache)
Bildpruefung: 34000/255158 (34000 aus Cache)
Bildpruefung: 34500/255158 (34500 aus Cache)
Bildpruefung: 35000/255158 (35000 aus Cache)
Bildpruefung: 35500/255158 (35500 aus Cache)
Bildpruefung: 36000/255158 (36000 aus Cache)
Bildpruefung: 36500/255158 (36500 aus Cache)
Bildpruefung: 37000/255158 (37000 aus Cache)
Bildpruefung: 37500/255158 (37500 aus Cache)
Bildpruefung: 38000/255158 (38000 aus Cache)
Bildpruefung: 38500/255158 (38500 aus Cache)
Bildpruefung: 39000/255158 (39000 aus Cache)
Bildpruefung: 39500/255158 (39500 aus Cache)
Bildpruefung: 40000/255158 (40000 aus Cache)
Bildpruefung: 40500/255158 (40500 aus Cache)
Bildpruefung: 41000/255158 (41000 aus Cache)
Bildpruefung: 41500/255158 (41500 aus Cache)
Bildpruefung: 42000/255158 (42000 aus Cache)
Bildpruefung: 42500/255158 (42500 aus Cache)
Bildpruefung: 43000/255158 (43000 aus Cache)
Bildpruefung: 43500/255158 (43500 aus Cache)
Bildpruefung: 44000/255158 (44000 aus Cache)
Bildpruefung: 44500/255158 (44500 aus Cache)
Bildpruefung: 45000/255158 (45000 aus Cache)
Bildpruefung: 45500/255158 (45500 aus Cache)
Bildpruefung: 46000/255158 (46000 aus Cache)
Bildpruefung: 46500/255158 (46500 aus Cache)
Bildpruefung: 47000/255158 (47000 aus Cache)
Bildpruefung: 47500/255158 (47500 aus Cache)
Bildpruefung: 48000/255158 (48000 aus Cache)
Bildpruefung: 48500/255158 (48500 aus Cache)
Bildpruefung: 49000/255158 (49000 aus Cache)
Bildpruefung: 49500/255158 (49500 aus Cache)
Bildpruefung: 50000/255158 (50000 aus Cache)
Bildpruefung: 50500/255158 (50500 aus Cache)
Bildpruefung: 51000/255158 (51000 aus Cache)
Bildpruefung: 51500/255158 (51500 aus Cache)
Bildpruefung: 52000/255158 (52000 aus Cache)
Bildpruefung: 52500/255158 (52500 aus Cache)
Bildpruefung: 53000/255158 (53000 aus Cache)
Bildpruefung: 53500/255158 (53500 aus Cache)
Bildpruefung: 54000/255158 (54000 aus Cache)
Bildpruefung: 54500/255158 (54500 aus Cache)
Bildpruefung: 55000/255158 (55000 aus Cache)
Bildpruefung: 55500/255158 (55500 aus Cache)
Bildpruefung: 56000/255158 (56000 aus Cache)
Bildpruefung: 56500/255158 (56500 aus Cache)
Bildpruefung: 57000/255158 (57000 aus Cache)
Bildpruefung: 57500/255158 (57500 aus Cache)
Bildpruefung: 58000/255158 (58000 aus Cache)
Bildpruefung: 58500/255158 (58500 aus Cache)
Bildpruefung: 59000/255158 (59000 aus Cache)
Bildpruefung: 59500/255158 (59500 aus Cache)
Bildpruefung: 60000/255158 (60000 aus Cache)
Bildpruefung: 60500/255158 (60500 aus Cache)
Bildpruefung: 61000/255158 (61000 aus Cache)
Bildpruefung: 61500/255158 (61500 aus Cache)
Bildpruefung: 62000/255158 (62000 aus Cache)
Bildpruefung: 62500/255158 (62500 aus Cache)
Bildpruefung: 63000/255158 (63000 aus Cache)
Bildpruefung: 63500/255158 (63500 aus Cache)
Bildpruefung: 64000/255158 (64000 aus Cache)
Bildpruefung: 64500/255158 (64500 aus Cache)
Bildpruefung: 65000/255158 (65000 aus Cache)
Bildpruefung: 65500/255158 (65500 aus Cache)
Bildpruefung: 66000/255158 (66000 aus Cache)
Bildpruefung: 66500/255158 (66500 aus Cache)
Bildpruefung: 67000/255158 (67000 aus Cache)
Bildpruefung: 67500/255158 (67500 aus Cache)
Bildpruefung: 68000/255158 (68000 aus Cache)
Bildpruefung: 68500/255158 (68500 aus Cache)
Bildpruefung: 69000/255158 (69000 aus Cache)
Bildpruefung: 69500/255158 (69500 aus Cache)
Bildpruefung: 70000/255158 (70000 aus Cache)
Bildpruefung: 70500/255158 (70500 aus Cache)
Bildpruefung: 71000/255158 (71000 aus Cache)
Bildpruefung: 71500/255158 (71500 aus Cache)
Bildpruefung: 72000/255158 (72000 aus Cache)
Bildpruefung: 72500/255158 (72500 aus Cache)
Bildpruefung: 73000/255158 (73000 aus Cache)
Bildpruefung: 73500/255158 (73500 aus Cache)
Bildpruefung: 74000/255158 (74000 aus Cache)
Bildpruefung: 74500/255158 (74500 aus Cache)
Bildpruefung: 75000/255158 (75000 aus Cache)
Bildpruefung: 75500/255158 (75500 aus Cache)
Bildpruefung: 76000/255158 (76000 aus Cache)
Bildpruefung: 76500/255158 (76500 aus Cache)
Bildpruefung: 77000/255158 (77000 aus Cache)
Bildpruefung: 77500/255158 (77500 aus Cache)
Bildpruefung: 78000/255158 (78000 aus Cache)
Bildpruefung: 78500/255158 (78500 aus Cache)
Bildpruefung: 79000/255158 (79000 aus Cache)
Bildpruefung: 79500/255158 (79500 aus Cache)
Bildpruefung: 80000/255158 (80000 aus Cache)
Bildpruefung: 80500/255158 (80500 aus Cache)
Bildpruefung: 81000/255158 (81000 aus Cache)
Bildpruefung: 81500/255158 (81500 aus Cache)
Bildpruefung: 82000/255158 (82000 aus Cache)
Bildpruefung: 82500/255158 (82500 aus Cache)
Bildpruefung: 83000/255158 (83000 aus Cache)
Bildpruefung: 83500/255158 (83500 aus Cache)
Bildpruefung: 84000/255158 (84000 aus Cache)
Bildpruefung: 84500/255158 (84500 aus Cache)
Bildpruefung: 85000/255158 (85000 aus Cache)
Bildpruefung: 85500/255158 (85500 aus Cache)
Bildpruefung: 86000/255158 (86000 aus Cache)
Bildpruefung: 86500/255158 (86500 aus Cache)
Bildpruefung: 87000/255158 (87000 aus Cache)
Bildpruefung: 87500/255158 (87500 aus Cache)
Bildpruefung: 88000/255158 (88000 aus Cache)
Bildpruefung: 88500/255158 (88500 aus Cache)
Bildpruefung: 89000/255158 (89000 aus Cache)
Bildpruefung: 89500/255158 (89500 aus Cache)
Bildpruefung: 90000/255158 (90000 aus Cache)
Bildpruefung: 90500/255158 (90500 aus Cache)
Bildpruefung: 91000/255158 (91000 aus Cache)
Bildpruefung: 91500/255158 (91500 aus Cache)
Bildpruefung: 92000/255158 (92000 aus Cache)
Bildpruefung: 92500/255158 (92500 aus Cache)
Bildpruefung: 93000/255158 (93000 aus Cache)
Bildpruefung: 93500/255158 (93500 aus Cache)
Bildpruefung: 94000/255158 (94000 aus Cache)
Bildpruefung: 94500/255158 (94500 aus Cache)
Bildpruefung: 95000/255158 (95000 aus Cache)
Bildpruefung: 95500/255158 (95500 aus Cache)
Bildpruefung: 96000/255158 (96000 aus Cache)
Bildpruefung: 96500/255158 (96500 aus Cache)
Bildpruefung: 97000/255158 (97000 aus Cache)
Bildpruefung: 97500/255158 (97500 aus Cache)
Bildpruefung: 98000/255158 (98000 aus Cache)
Bildpruefung: 98500/255158 (98500 aus Cache)
Bildpruefung: 99000/255158 (99000 aus Cache)
Bildpruefung: 99500/255158 (99500 aus Cache)
Bildpruefung: 100000/255158 (100000 aus Cache)
Bildpruefung: 100500/255158 (100500 aus Cache)
Bildpruefung: 101000/255158 (101000 aus Cache)
Bildpruefung: 101500/255158 (101500 aus Cache)
Bildpruefung: 102000/255158 (102000 aus Cache)
Bildpruefung: 102500/255158 (102500 aus Cache)
Bildpruefung: 103000/255158 (103000 aus Cache)
Bildpruefung: 103500/255158 (103500 aus Cache)
Bildpruefung: 104000/255158 (104000 aus Cache)
Bildpruefung: 104500/255158 (104500 aus Cache)
Bildpruefung: 105000/255158 (105000 aus Cache)
Bildpruefung: 105500/255158 (105500 aus Cache)
Bildpruefung: 106000/255158 (106000 aus Cache)
Bildpruefung: 106500/255158 (106500 aus Cache)
Bildpruefung: 107000/255158 (107000 aus Cache)
Bildpruefung: 107500/255158 (107500 aus Cache)
Bildpruefung: 108000/255158 (108000 aus Cache)
Bildpruefung: 108500/255158 (108500 aus Cache)
Bildpruefung: 109000/255158 (109000 aus Cache)
Bildpruefung: 109500/255158 (109500 aus Cache)
Bildpruefung: 110000/255158 (110000 aus Cache)
Bildpruefung: 110500/255158 (110500 aus Cache)
Bildpruefung: 111000/255158 (111000 aus Cache)
Bildpruefung: 111500/255158 (111500 aus Cache)
Bildpruefung: 112000/255158 (112000 aus Cache)
Bildpruefung: 112500/255158 (112500 aus Cache)
Bildpruefung: 113000/255158 (113000 aus Cache)
Bildpruefung: 113500/255158 (113500 aus Cache)
Bildpruefung: 114000/255158 (114000 aus Cache)
Bildpruefung: 114500/255158 (114500 aus Cache)
Bildpruefung: 115000/255158 (115000 aus Cache)
Bildpruefung: 115500/255158 (115500 aus Cache)
Bildpruefung: 116000/255158 (116000 aus Cache)
Bildpruefung: 116500/255158 (116500 aus Cache)
Bildpruefung: 117000/255158 (117000 aus Cache)
Bildpruefung: 117500/255158 (117500 aus Cache)
Bildpruefung: 118000/255158 (118000 aus Cache)
Bildpruefung: 118500/255158 (118500 aus Cache)
Bildpruefung: 119000/255158 (119000 aus Cache)
Bildpruefung: 119500/255158 (119500 aus Cache)
Bildpruefung: 120000/255158 (120000 aus Cache)
Bildpruefung: 120500/255158 (120500 aus Cache)
Bildpruefung: 121000/255158 (121000 aus Cache)
Bildpruefung: 121500/255158 (121500 aus Cache)
Bildpruefung: 122000/255158 (122000 aus Cache)
Bildpruefung: 122500/255158 (122500 aus Cache)
Bildpruefung: 123000/255158 (123000 aus Cache)
Bildpruefung: 123500/255158 (123500 aus Cache)
Bildpruefung: 124000/255158 (124000 aus Cache)
Bildpruefung: 124500/255158 (124500 aus Cache)
Bildpruefung: 125000/255158 (125000 aus Cache)
Bildpruefung: 125500/255158 (125500 aus Cache)
Bildpruefung: 126000/255158 (126000 aus Cache)
Bildpruefung: 126500/255158 (126500 aus Cache)
Bildpruefung: 127000/255158 (127000 aus Cache)
Bildpruefung: 127500/255158 (127500 aus Cache)
Bildpruefung: 128000/255158 (128000 aus Cache)
Bildpruefung: 128500/255158 (128500 aus Cache)
Bildpruefung: 129000/255158 (129000 aus Cache)
Bildpruefung: 129500/255158 (129500 aus Cache)
Bildpruefung: 130000/255158 (130000 aus Cache)
Bildpruefung: 130500/255158 (130500 aus Cache)
Bildpruefung: 131000/255158 (131000 aus Cache)
Bildpruefung: 131500/255158 (131500 aus Cache)
Bildpruefung: 132000/255158 (132000 aus Cache)
Bildpruefung: 132500/255158 (132500 aus Cache)
Bildpruefung: 133000/255158 (133000 aus Cache)
Bildpruefung: 133500/255158 (133500 aus Cache)
Bildpruefung: 134000/255158 (134000 aus Cache)
Bildpruefung: 134500/255158 (134500 aus Cache)
Bildpruefung: 135000/255158 (135000 aus Cache)
Bildpruefung: 135500/255158 (135500 aus Cache)
Bildpruefung: 136000/255158 (136000 aus Cache)
Bildpruefung: 136500/255158 (136500 aus Cache)
Bildpruefung: 137000/255158 (137000 aus Cache)
Bildpruefung: 137500/255158 (137500 aus Cache)
Bildpruefung: 138000/255158 (138000 aus Cache)
Bildpruefung: 138500/255158 (138500 aus Cache)
Bildpruefung: 139000/255158 (139000 aus Cache)
Bildpruefung: 139500/255158 (139500 aus Cache)
Bildpruefung: 140000/255158 (140000 aus Cache)
Bildpruefung: 140500/255158 (140500 aus Cache)
Bildpruefung: 141000/255158 (141000 aus Cache)
Bildpruefung: 141500/255158 (141500 aus Cache)
Bildpruefung: 142000/255158 (142000 aus Cache)
Bildpruefung: 142500/255158 (142500 aus Cache)
Bildpruefung: 143000/255158 (143000 aus Cache)
Bildpruefung: 143500/255158 (143500 aus Cache)
Bildpruefung: 144000/255158 (144000 aus Cache)
Bildpruefung: 144500/255158 (144500 aus Cache)
Bildpruefung: 145000/255158 (145000 aus Cache)
Bildpruefung: 145500/255158 (145500 aus Cache)
Bildpruefung: 146000/255158 (146000 aus Cache)
Bildpruefung: 146500/255158 (146500 aus Cache)
Bildpruefung: 147000/255158 (147000 aus Cache)
Bildpruefung: 147500/255158 (147500 aus Cache)
Bildpruefung: 148000/255158 (148000 aus Cache)
Bildpruefung: 148500/255158 (148500 aus Cache)
Bildpruefung: 149000/255158 (149000 aus Cache)
Bildpruefung: 149500/255158 (149500 aus Cache)
Bildpruefung: 150000/255158 (150000 aus Cache)
Bildpruefung: 150500/255158 (150500 aus Cache)
Bildpruefung: 151000/255158 (151000 aus Cache)
Bildpruefung: 151500/255158 (151500 aus Cache)
Bildpruefung: 152000/255158 (152000 aus Cache)
Bildpruefung: 152500/255158 (152500 aus Cache)
Bildpruefung: 153000/255158 (153000 aus Cache)
Bildpruefung: 153500/255158 (153500 aus Cache)
Bildpruefung: 154000/255158 (154000 aus Cache)
Bildpruefung: 154500/255158 (154500 aus Cache)
Bildpruefung: 155000/255158 (155000 aus Cache)
Bildpruefung: 155500/255158 (155500 aus Cache)
Bildpruefung: 156000/255158 (156000 aus Cache)
Bildpruefung: 156500/255158 (156500 aus Cache)
Bildpruefung: 157000/255158 (157000 aus Cache)
Bildpruefung: 157500/255158 (157500 aus Cache)
Bildpruefung: 158000/255158 (158000 aus Cache)
Bildpruefung: 158500/255158 (158500 aus Cache)
Bildpruefung: 159000/255158 (159000 aus Cache)
Bildpruefung: 159500/255158 (159500 aus Cache)
Bildpruefung: 160000/255158 (160000 aus Cache)
Bildpruefung: 160500/255158 (160500 aus Cache)
Bildpruefung: 161000/255158 (161000 aus Cache)
Bildpruefung: 161500/255158 (161500 aus Cache)
Bildpruefung: 162000/255158 (162000 aus Cache)
Bildpruefung: 162500/255158 (162500 aus Cache)
Bildpruefung: 163000/255158 (163000 aus Cache)
Bildpruefung: 163500/255158 (163500 aus Cache)
Bildpruefung: 164000/255158 (164000 aus Cache)
Bildpruefung: 164500/255158 (164500 aus Cache)
Bildpruefung: 165000/255158 (165000 aus Cache)
Bildpruefung: 165500/255158 (165500 aus Cache)
Bildpruefung: 166000/255158 (166000 aus Cache)
Bildpruefung: 166500/255158 (166500 aus Cache)
Bildpruefung: 167000/255158 (167000 aus Cache)
Bildpruefung: 167500/255158 (167500 aus Cache)
Bildpruefung: 168000/255158 (168000 aus Cache)
Bildpruefung: 168500/255158 (168500 aus Cache)
Bildpruefung: 169000/255158 (169000 aus Cache)
Bildpruefung: 169500/255158 (169500 aus Cache)
Bildpruefung: 170000/255158 (170000 aus Cache)
Bildpruefung: 170500/255158 (170500 aus Cache)
Bildpruefung: 171000/255158 (171000 aus Cache)
Bildpruefung: 171500/255158 (171500 aus Cache)
Bildpruefung: 172000/255158 (172000 aus Cache)
Bildpruefung: 172500/255158 (172500 aus Cache)
Bildpruefung: 173000/255158 (173000 aus Cache)
Bildpruefung: 173500/255158 (173500 aus Cache)
Bildpruefung: 174000/255158 (174000 aus Cache)
Bildpruefung: 174500/255158 (174500 aus Cache)
Bildpruefung: 175000/255158 (175000 aus Cache)
Bildpruefung: 175500/255158 (175500 aus Cache)
Bildpruefung: 176000/255158 (176000 aus Cache)
Bildpruefung: 176500/255158 (176500 aus Cache)
Bildpruefung: 177000/255158 (177000 aus Cache)
Bildpruefung: 177500/255158 (177500 aus Cache)
Bildpruefung: 178000/255158 (178000 aus Cache)
Bildpruefung: 178500/255158 (178500 aus Cache)
Bildpruefung: 179000/255158 (179000 aus Cache)
Bildpruefung: 179500/255158 (179500 aus Cache)
Bildpruefung: 180000/255158 (180000 aus Cache)
Bildpruefung: 180500/255158 (180500 aus Cache)
Bildpruefung: 181000/255158 (181000 aus Cache)
Bildpruefung: 181500/255158 (181500 aus Cache)
Bildpruefung: 182000/255158 (182000 aus Cache)
Bildpruefung: 182500/255158 (182500 aus Cache)
Bildpruefung: 183000/255158 (183000 aus Cache)
Bildpruefung: 183500/255158 (183500 aus Cache)
Bildpruefung: 184000/255158 (184000 aus Cache)
Bildpruefung: 184500/255158 (184500 aus Cache)
Bildpruefung: 185000/255158 (185000 aus Cache)
Bildpruefung: 185500/255158 (185500 aus Cache)
Bildpruefung: 186000/255158 (186000 aus Cache)
Bildpruefung: 186500/255158 (186500 aus Cache)
Bildpruefung: 187000/255158 (187000 aus Cache)
Bildpruefung: 187500/255158 (187500 aus Cache)
Bildpruefung: 188000/255158 (188000 aus Cache)
Bildpruefung: 188500/255158 (188500 aus Cache)
Bildpruefung: 189000/255158 (189000 aus Cache)
Bildpruefung: 189500/255158 (189500 aus Cache)
Bildpruefung: 190000/255158 (190000 aus Cache)
Bildpruefung: 190500/255158 (190500 aus Cache)
Bildpruefung: 191000/255158 (191000 aus Cache)
Bildpruefung: 191500/255158 (191500 aus Cache)
Bildpruefung: 192000/255158 (192000 aus Cache)
Bildpruefung: 192500/255158 (192500 aus Cache)
Bildpruefung: 193000/255158 (193000 aus Cache)
Bildpruefung: 193500/255158 (193500 aus Cache)
Bildpruefung: 194000/255158 (194000 aus Cache)
Bildpruefung: 194500/255158 (194500 aus Cache)
Bildpruefung: 195000/255158 (195000 aus Cache)
Bildpruefung: 195500/255158 (195500 aus Cache)
Bildpruefung: 196000/255158 (196000 aus Cache)
Bildpruefung: 196500/255158 (196500 aus Cache)
Bildpruefung: 197000/255158 (197000 aus Cache)
Bildpruefung: 197500/255158 (197500 aus Cache)
Bildpruefung: 198000/255158 (198000 aus Cache)
Bildpruefung: 198500/255158 (198500 aus Cache)
Bildpruefung: 199000/255158 (199000 aus Cache)
Bildpruefung: 199500/255158 (199500 aus Cache)
Bildpruefung: 200000/255158 (200000 aus Cache)
Bildpruefung: 200500/255158 (200500 aus Cache)
Bildpruefung: 201000/255158 (201000 aus Cache)
Bildpruefung: 201500/255158 (201500 aus Cache)
Bildpruefung: 202000/255158 (202000 aus Cache)
Bildpruefung: 202500/255158 (202500 aus Cache)
Bildpruefung: 203000/255158 (203000 aus Cache)
Bildpruefung: 203500/255158 (203500 aus Cache)
Bildpruefung: 204000/255158 (204000 aus Cache)
Bildpruefung: 204500/255158 (204500 aus Cache)
Bildpruefung: 205000/255158 (205000 aus Cache)
Bildpruefung: 205500/255158 (205500 aus Cache)
Bildpruefung: 206000/255158 (206000 aus Cache)
Bildpruefung: 206500/255158 (206500 aus Cache)
Bildpruefung: 207000/255158 (207000 aus Cache)
Bildpruefung: 207500/255158 (207500 aus Cache)
Bildpruefung: 208000/255158 (208000 aus Cache)
Bildpruefung: 208500/255158 (208500 aus Cache)
Bildpruefung: 209000/255158 (209000 aus Cache)
Bildpruefung: 209500/255158 (209500 aus Cache)
Bildpruefung: 210000/255158 (210000 aus Cache)
Bildpruefung: 210500/255158 (210500 aus Cache)
Bildpruefung: 211000/255158 (211000 aus Cache)
Bildpruefung: 211500/255158 (211500 aus Cache)
Bildpruefung: 212000/255158 (212000 aus Cache)
Bildpruefung: 212500/255158 (212500 aus Cache)
Bildpruefung: 213000/255158 (213000 aus Cache)
Bildpruefung: 213500/255158 (213500 aus Cache)
Bildpruefung: 214000/255158 (214000 aus Cache)
Bildpruefung: 214500/255158 (214500 aus Cache)
Bildpruefung: 215000/255158 (215000 aus Cache)
Bildpruefung: 215500/255158 (215500 aus Cache)
Bildpruefung: 216000/255158 (216000 aus Cache)
Bildpruefung: 216500/255158 (216500 aus Cache)
Bildpruefung: 217000/255158 (217000 aus Cache)

  Modus  Gepruefte Dateien  Nicht lesbar  Exakte Duplikatgruppen
0  full             255158             0                    1247

## 3. Formate und Bildqualität
Bilddimensionen, Farbmodus, Helligkeit und Kantenvariation werden beschreibend geprüft. Es werden daraus keine automatischen Ausschlussgrenzen abgeleitet.

In [3]:
display(audit.groupby(["width", "height", "mode"], dropna=False)
        .size().rename("n").reset_index().sort_values("n", ascending=False).head(10))
display(audit[["brightness", "edge_variance"]].describe().round(2))
errors = audit.loc[~audit["readable"], ["relative_path", "error"]]
print("Fehlerhafte Dateien:", len(errors))
display(errors.head(10))

   width  height mode       n
0    640     480  RGB  255158

       brightness  edge_variance
count   255158.00      255158.00
mean       128.90        1303.28
std         15.61         618.80
min         33.52         188.75
25%        118.05         951.66
50%        130.30        1175.66
75%        140.14        1483.77
max        175.27        6287.72

Fehlerhafte Dateien: 0

Empty DataFrame
Columns: [relative_path, error]
Index: []

## 4. Identische Inhalte unterscheiden
Zwei Prüfungen unterscheiden dateiidentische Inhalte und identische dekodierte RGB-Pixel. Wiederkehrende Dateinamen werden separat erfasst und gelten nicht automatisch als Duplikate. Eine Entscheidung über den Ausschluss erfolgt erst im folgenden Kurationsschritt.

In [4]:
exact = audit.loc[audit["sha256_group_size"].gt(1)]
pixel_equal = audit.loc[audit["pixel_sha256_group_size"].gt(1)]
display(pd.DataFrame({
    "Pruefung": ["Dateiidentische Gruppen", "Pixelidentische Gruppen", "Wiederkehrende Dateinamen"],
    "Anzahl": [exact["sha256"].nunique(), pixel_equal["pixel_sha256"].nunique(),
               int(audit["filename"].value_counts().gt(1).sum())],
}))
display(pd.DataFrame({
    "Pruefung": [
        "Exakte Duplikatdateien",
        "Exakte Duplikatgruppen",
        "Ordneruebergreifende exakte Dateien",
        "Pixelidentische Gruppen",
        "Wiederkehrende Dateinamen",
    ],
    "Anzahl": [
        summary["n_exact_duplicate_files"],
        summary["n_exact_duplicate_groups"],
        summary["n_cross_folder_exact_files"],
        pixel_equal["pixel_sha256"].nunique(),
        summary["n_repeated_filenames"],
    ],
}))

                    Pruefung  Anzahl
0    Dateiidentische Gruppen    1247
1    Pixelidentische Gruppen    1247
2  Wiederkehrende Dateinamen    1079

                              Pruefung  Anzahl
0               Exakte Duplikatdateien   10084
1               Exakte Duplikatgruppen    1247
2  Ordneruebergreifende exakte Dateien     142
3              Pixelidentische Gruppen    1247
4            Wiederkehrende Dateinamen    1079

## 5. Audit abschließen
Nur ein vollständiger Audit wird in Notebook 03 verwendet. Fehlerhafte Dateien und Duplikate werden hier noch nicht entfernt.

In [5]:
print("Audit abgeschlossen.")
print("Geprüfte Dateien:", summary["n_files_audited"])
print("Nicht lesbar:", summary["n_unreadable_files"])

Audit abgeschlossen.
Geprüfte Dateien: 255158
Nicht lesbar: 0

## Ergebnis

Der vollständige Audit umfasst 255.158 Bilder. Alle Dateien konnten erfolgreich dekodiert werden und liegen einheitlich als RGB-Bilder mit 640 × 480 Pixeln vor. Es wurden 10.084 Dateien in 1.247 exakten Duplikatgruppen identifiziert; davon betreffen 142 Dateien ordnerübergreifende Duplikate. Die Rohdaten wurden nicht verändert. Die Entscheidung über den Umgang mit diesen Fällen erfolgt getrennt im Kurationsschritt.